language: node_js
node_js:
  - 12
addons:
  apt:
    packages:
      - libgconf-2-4
cache:
  npm: true
  directories:
    - ~/.cache

script:
  - npm run lint -- --no-fix
  - npm test
  - npm run build

before_deploy: scripts/before-deploy.sh

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    local_dir: dist/web/root
    on:
      branch: master
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN_SUPERHEROWALLET
    keep_history: true
    local_dir: dist/web/root
    repo: superherowallet/wallet
    target_branch: master
    on:
      branch: develop
  - provider: script
    skip_cleanup: true
    script: scripts/deploy-stage.sh
    on:
      all_branches: true
