export default ({
  migrations,
  current,
  transactions,
  currencies,
  userNetworks,
  names,
  languages,
  nextCurrenciesFetch,
  tip,
  backedUpSeed,
  mnemonic,
  saveErrorLog,
  tourStartBar,
  invites,
  notificationSettings,
  permissions,
  fungibleTokens,
  accounts: { accs, accountSelectedIdx, accountCount } = {},
  cardMinified,
}) => ({
  migrations,
  current,
  transactions,
  currencies,
  userNetworks,
  names,
  languages,
  nextCurrenciesFetch,
  tip,
  backedUpSeed,
  mnemonic,
  saveErrorLog,
  tourStartBar,
  invites,
  notificationSettings,
  permissions,
  fungibleTokens,
  accounts: { accs, accountSelectedIdx, accountCount },
  cardMinified,
});
