export default ({
  migrations,
  transactions: { pending } = {},
  names,
  languages,
  backedUpSeed,
  mnemonic,
  saveErrorLog,
  invites,
  notificationSettings,
  permissions,
  fungibleTokens,
  accounts: { list, activeIdx, hdWallet: { nextAccountIdx } = {} } = {},
  hiddenCards,
}) => ({
  migrations,
  transactions: { pending, loaded: [], nextPageUrl: '' },
  names,
  languages,
  backedUpSeed,
  mnemonic,
  saveErrorLog,
  invites,
  notificationSettings,
  permissions,
  fungibleTokens,
  accounts: { list, activeIdx, hdWallet: { nextAccountIdx } },
  hiddenCards,
});
