export default ({
  migrations,
  current,
  transactions: { pending } = {},
  currencies,
  userNetworks,
  names,
  languages,
  backedUpSeed,
  mnemonic,
  saveErrorLog,
  invites,
  notificationSettings,
  permissions,
  fungibleTokens,
  accounts: { list, activeIdx, hdWallet: { nextAccountIdx } = {} } = {},
  cardMinified,
}) => ({
  migrations,
  current,
  transactions: { pending, loaded: [], nextPageUrl: '' },
  currencies,
  userNetworks,
  names,
  languages,
  backedUpSeed,
  mnemonic,
  saveErrorLog,
  invites,
  notificationSettings,
  permissions,
  fungibleTokens,
  accounts: { list, activeIdx, hdWallet: { nextAccountIdx } },
  cardMinified,
});
