name: Build and deploy
on: [push, pull_request]
jobs:
  main:
    runs-on: ubuntu-latest
    env:
      APP_NAME: wallet
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 100
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install app dependencies
        run: npm ci
      - name: Build Ionic Vue android app
        run: npm run build:android
      - name: Build android apk
        run: cd android && ./gradlew assembleDebug
      - run: |
          npm run build:web
          npm run build:extension
          npm run build-zip
          cp -r dist/web/root dist-stage
          mv dist-zip dist-stage/artifacts
          mkdir -p tests/e2e/screenshots
          mv tests/e2e/screenshots dist-stage/artifacts/screenshots
          mv tests/pages/index.html dist-stage/artifacts/deeplink-test.html
          cp -r ./android/app/build/outputs/apk/debug ./dist-stage/artifacts/android
      - run: cp ./dist/web/root/index.html ./dist/web/root/404.html
      - name: Deploy to production
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist/web/root
          cname: wallet.superhero.com

      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Release ${{ github.ref }}
      - uses: alexellis/upload-assets@0.4.0
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_paths: '["./dist-stage/artifacts/superhero-wallet-*"]'

      - uses: rlespinasse/github-slug-action@v4.x
      - name: Deploy to stage
        uses: easingthemes/ssh-deploy@v4.1.8
        if: github.event_name == 'push'
        env:
          SSH_PRIVATE_KEY: ${{ secrets.STAGE_PRIVATE_KEY }}
          SOURCE: dist-stage/
          REMOTE_HOST: z52da5wt.xyz
          REMOTE_USER: root
          REMOTE_PORT: 2022
          TARGET: ${{ format('/data/{0}/{1}', env.APP_NAME, env.GITHUB_REF_SLUG_URL) }}
      - uses: unsplash/comment-on-pr@a9bf050e744c8282dee4bb0dbcf063186d8316c4
        if: github.event_name == 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOST: ${{ format('{0}.{1}.z52da5wt.xyz', env.GITHUB_HEAD_REF_SLUG_URL, env.APP_NAME) }}
        with:
          msg: Deployed to [${{ env.HOST }}](https://${{ env.HOST }}), [artifacts](https://${{ env.HOST }}/artifacts)
          check_for_duplicate_msg: true
