name: Test
on: [push, pull_request]
jobs:
  main:
    runs-on: ubuntu-latest
    env:
      APP_NAME: wallet
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 100
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install app dependencies
        run: npm ci
      - name: Run Commitlint
        if: github.event_name == 'pull_request'
        env:
          HEAD: ${{ github.event.pull_request.head.sha }}
          BASE: ${{ github.event.pull_request.base.sha }}
        run: npx commitlint --from $BASE --to $HEAD --verbose
      - run: npx cross-env NODE_ENV=production npm run lint:vue && npm run lint:css
      - run: npm test
